from __future__ import annotations

from pathlib import Path
from typing import Any

import utils


class TensorBoardCallback:
    """Write epoch metrics to TensorBoard when available."""

    def __init__(self, *, log_subdir: str = "tensorboard") -> None:
        self.log_subdir = log_subdir
        self._writer = None
        self._enabled = True

    def _get_writer(self, trainer: Any):
        if not getattr(trainer, "is_main_process", True):
            return None
        if not self._enabled:
            return None
        if self._writer is not None:
            return self._writer
        try:
            from torch.utils.tensorboard import SummaryWriter
        except Exception:
            self._enabled = False
            return None
        log_dir = Path(trainer.output_dir) / self.log_subdir
        log_dir.mkdir(parents=True, exist_ok=True)
        self._writer = SummaryWriter(log_dir=str(log_dir))
        return self._writer

    def on_epoch_start(self, *, epoch: int, trainer: Any) -> None:
        del epoch, trainer
        return None

    def on_epoch_end(self, *, epoch: int, metrics: dict, state: dict, trainer: Any) -> None:
        del state
        writer = self._get_writer(trainer)
        if writer is None:
            return
        global_step = getattr(trainer, "global_step", epoch)
        for key, value in metrics.items():
            if isinstance(value, (int, float)):
                writer.add_scalar(f"metrics/{key}", float(value), int(global_step))
        optimizer = getattr(trainer, "optimizer", None)
        if optimizer is not None and getattr(optimizer, "param_groups", None):
            lr = optimizer.param_groups[0].get("lr")
            if lr is not None:
                writer.add_scalar("optimizer/lr", float(lr), int(global_step))
        writer.flush()

    def on_train_end(self, *, trainer: Any) -> None:
        del trainer
        if self._writer is not None:
            self._writer.close()
            self._writer = None


class CheckpointCallback:
    """Save periodic and best checkpoints from trainer state."""

    def __init__(
        self,
        *,
        filename_prefix: str = "model",
        monitor: str = "loss",
        mode: str = "min",
        save_every: int = 0,
    ) -> None:
        self.filename_prefix = filename_prefix
        self.monitor = monitor
        self.mode = mode
        self.save_every = max(0, int(save_every))
        self.best_metric = float("inf") if mode == "min" else float("-inf")

    def on_epoch_start(self, *, epoch: int, trainer: Any) -> None:
        return None

    def on_epoch_end(self, *, epoch: int, metrics: dict, state: dict, trainer: Any) -> None:
        if not getattr(trainer, "is_main_process", True):
            return
        output_dir = Path(trainer.output_dir)
        last_path = output_dir / f"{self.filename_prefix}_last.pt"
        utils.save_checkpoint(state, last_path)

        if self.save_every > 0 and epoch % self.save_every == 0:
            epoch_dir = output_dir / "epochs" / f"epoch{epoch:04d}"
            epoch_dir.mkdir(parents=True, exist_ok=True)
            utils.save_checkpoint(state, epoch_dir / "epoch.pt")

        current = metrics.get(self.monitor)
        if current is None:
            return

        improved = current < self.best_metric if self.mode == "min" else current > self.best_metric
        if improved:
            self.best_metric = current
            state["best_metric"] = self.best_metric
            best_path = output_dir / f"{self.filename_prefix}_best.pt"
            utils.save_checkpoint(state, best_path)

    def on_train_end(self, *, trainer: Any) -> None:
        return None


class VisualizationCallback:
    """Save visualization artifacts generated by trainer-provided callback."""

    def __init__(self, *, every_n_epochs: int = 1, output_subdir: str = "epochs") -> None:
        self.every_n_epochs = max(1, int(every_n_epochs))
        self.output_subdir = output_subdir

    def on_epoch_start(self, *, epoch: int, trainer: Any) -> None:
        return None

    def on_epoch_end(self, *, epoch: int, metrics: dict, state: dict, trainer: Any) -> None:
        if not getattr(trainer, "is_main_process", True):
            return
        if epoch % self.every_n_epochs != 0:
            return
        render_fn = getattr(trainer, "render_visuals", None)
        if not callable(render_fn):
            return

        output_root = Path(trainer.output_dir) / self.output_subdir / f"epoch{epoch:04d}"
        output_root.mkdir(parents=True, exist_ok=True)
        ema_scope = getattr(trainer, "ema_scope", None)
        if callable(ema_scope):
            with ema_scope():
                render_fn(output_root=output_root, epoch=epoch, metrics=metrics, state=state)
            return
        render_fn(output_root=output_root, epoch=epoch, metrics=metrics, state=state)

    def on_train_end(self, *, trainer: Any) -> None:
        return None


class MetricsCSVCallback:
    """Append epoch metrics to a CSV file."""

    def __init__(self, *, filename: str = "metrics.csv", metric_keys: list[str] | None = None) -> None:
        self.filename = filename
        self.metric_keys = metric_keys

    def on_epoch_start(self, *, epoch: int, trainer: Any) -> None:
        return None

    @staticmethod
    def _lr(optimizer) -> float | None:
        if optimizer is None or not getattr(optimizer, "param_groups", None):
            return None
        lr = optimizer.param_groups[0].get("lr")
        return None if lr is None else float(lr)

    def on_epoch_end(self, *, epoch: int, metrics: dict, state: dict, trainer: Any) -> None:
        if not getattr(trainer, "is_main_process", True):
            return
        output_dir = Path(trainer.output_dir)
        path = output_dir / self.filename
        lr = self._lr(getattr(trainer, "optimizer", None))
        row_metrics = dict(metrics)
        if lr is not None:
            row_metrics["lr"] = lr
        keys = self.metric_keys or sorted(row_metrics.keys())

        if not path.exists():
            header = "epoch," + ",".join(keys) + "\n"
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(header, encoding="utf-8")

        row = [str(epoch)]
        for key in keys:
            value = row_metrics.get(key)
            if value is None:
                row.append("")
            elif isinstance(value, (int, float)):
                row.append(f"{value:.6f}")
            else:
                row.append(str(value))

        with path.open("a", encoding="utf-8") as handle:
            handle.write(",".join(row) + "\n")

    def on_train_end(self, *, trainer: Any) -> None:
        return None


class MultiResolutionCallback:
    """Rebuild dataloaders on multi-resolution stage transitions."""

    def __init__(self) -> None:
        self._last_resolution: int | None = None

    def on_epoch_start(self, *, epoch: int, trainer: Any) -> None:
        schedule = getattr(trainer, "_resolution_schedule", None)
        if schedule is None:
            return
        rebuild = getattr(trainer, "request_dataloader_rebuild", None)
        if not callable(rebuild):
            rebuild = getattr(trainer, "_rebuild_dataloaders", None)
        if not callable(rebuild):
            raise AttributeError("Trainer does not expose a dataloader rebuild hook.")
        resolution = int(schedule.current_resolution(epoch))
        if self._last_resolution is None:
            self._last_resolution = resolution
            rebuild(target_resolution=resolution)
            return
        if resolution != self._last_resolution:
            self._last_resolution = resolution
            rebuild(target_resolution=resolution)

    def on_epoch_end(self, *, epoch: int, metrics: dict, state: dict, trainer: Any) -> None:
        _ = epoch, metrics, state, trainer
        return None

    def on_train_end(self, *, trainer: Any) -> None:
        _ = trainer
        return None


class StepMetricsCallback:
    """Append per-step telemetry to a CSV file."""

    def __init__(self, *, every_n_steps: int = 1, filename: str = "step_metrics.csv") -> None:
        self.every_n_steps = max(1, int(every_n_steps))
        self.filename = filename
        self._header_written = False

    @staticmethod
    def _grad_norm(optimizer) -> float:
        if optimizer is None:
            return 0.0
        sq_sum = 0.0
        for group in optimizer.param_groups:
            for param in group.get("params", ()):
                grad = getattr(param, "grad", None)
                if grad is None:
                    continue
                norm = float(grad.detach().norm(2).item())
                sq_sum += norm * norm
        return sq_sum ** 0.5

    @staticmethod
    def _lr(optimizer) -> float:
        if optimizer is None or not getattr(optimizer, "param_groups", None):
            return 0.0
        return float(optimizer.param_groups[0].get("lr", 0.0))

    def on_step_end(
        self,
        *,
        epoch: int,
        step: int,
        global_step: int,
        metrics: dict,
        trainer: Any,
    ) -> None:
        if not getattr(trainer, "is_main_process", True):
            return
        if int(global_step) % self.every_n_steps != 0:
            return

        path = Path(trainer.output_dir) / self.filename
        path.parent.mkdir(parents=True, exist_ok=True)
        optimizer = getattr(trainer, "optimizer", None)
        disc_optimizer = getattr(trainer, "disc_optimizer", None)
        scaler = getattr(trainer, "scaler", None)
        disc_scaler = getattr(trainer, "disc_scaler", None)
        batch_size = getattr(trainer, "_last_step_batch_size", None)
        step_seconds = getattr(trainer, "_last_step_seconds", None)
        imgs_per_sec = 0.0
        if step_seconds is not None and step_seconds > 0 and batch_size is not None:
            imgs_per_sec = float(batch_size) / float(step_seconds)

        row = {
            "epoch": int(epoch),
            "step": int(step),
            "global_step": int(global_step),
            "loss": float(metrics.get("loss", 0.0)),
            "lr": self._lr(optimizer),
            "grad_norm": self._grad_norm(optimizer),
            "disc_grad_norm": self._grad_norm(disc_optimizer),
            "scaler": float(scaler.get_scale()) if scaler is not None and hasattr(scaler, "get_scale") else 1.0,
            "disc_scaler": float(disc_scaler.get_scale()) if disc_scaler is not None and hasattr(disc_scaler, "get_scale") else 1.0,
            "imgs_per_sec": imgs_per_sec,
        }

        if not self._header_written and not path.exists():
            path.write_text(",".join(row.keys()) + "\n", encoding="utf-8")
        self._header_written = True
        with path.open("a", encoding="utf-8") as handle:
            handle.write(",".join(str(row[key]) for key in row.keys()) + "\n")
