from __future__ import annotations

from pathlib import Path
from typing import Any

import utils


class CheckpointCallback:
    """Save periodic and best checkpoints from trainer state."""

    def __init__(self, *, filename_prefix: str = "model", monitor: str = "loss", mode: str = "min") -> None:
        self.filename_prefix = filename_prefix
        self.monitor = monitor
        self.mode = mode
        self.best_metric = float("inf") if mode == "min" else float("-inf")

    def on_epoch_start(self, *, epoch: int, trainer: Any) -> None:
        return None

    def on_epoch_end(self, *, epoch: int, metrics: dict, state: dict, trainer: Any) -> None:
        output_dir = Path(trainer.output_dir)
        last_path = output_dir / f"{self.filename_prefix}_last.pt"
        utils.save_checkpoint(state, last_path)

        current = metrics.get(self.monitor)
        if current is None:
            return

        improved = current < self.best_metric if self.mode == "min" else current > self.best_metric
        if improved:
            self.best_metric = current
            state["best_metric"] = self.best_metric
            best_path = output_dir / f"{self.filename_prefix}_best.pt"
            utils.save_checkpoint(state, best_path)

    def on_train_end(self, *, trainer: Any) -> None:
        return None


class VisualizationCallback:
    """Save visualization artifacts generated by trainer-provided callback."""

    def __init__(self, *, every_n_epochs: int = 1, output_subdir: str = "epochs") -> None:
        self.every_n_epochs = max(1, int(every_n_epochs))
        self.output_subdir = output_subdir

    def on_epoch_start(self, *, epoch: int, trainer: Any) -> None:
        return None

    def on_epoch_end(self, *, epoch: int, metrics: dict, state: dict, trainer: Any) -> None:
        if epoch % self.every_n_epochs != 0:
            return
        render_fn = getattr(trainer, "render_visuals", None)
        if not callable(render_fn):
            return

        output_root = Path(trainer.output_dir) / self.output_subdir / f"epoch{epoch:04d}"
        output_root.mkdir(parents=True, exist_ok=True)
        render_fn(output_root=output_root, epoch=epoch, metrics=metrics, state=state)

    def on_train_end(self, *, trainer: Any) -> None:
        return None


class MetricsCSVCallback:
    """Append epoch metrics to a CSV file."""

    def __init__(self, *, filename: str = "metrics.csv", metric_keys: list[str] | None = None) -> None:
        self.filename = filename
        self.metric_keys = metric_keys

    def on_epoch_start(self, *, epoch: int, trainer: Any) -> None:
        return None

    def on_epoch_end(self, *, epoch: int, metrics: dict, state: dict, trainer: Any) -> None:
        output_dir = Path(trainer.output_dir)
        path = output_dir / self.filename
        keys = self.metric_keys or sorted(metrics.keys())

        if not path.exists():
            header = "epoch," + ",".join(keys) + "\n"
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(header, encoding="utf-8")

        row = [str(epoch)]
        for key in keys:
            value = metrics.get(key)
            if value is None:
                row.append("")
            elif isinstance(value, (int, float)):
                row.append(f"{value:.6f}")
            else:
                row.append(str(value))

        with path.open("a", encoding="utf-8") as handle:
            handle.write(",".join(row) + "\n")

    def on_train_end(self, *, trainer: Any) -> None:
        return None
