from __future__ import annotations

from pathlib import Path
from typing import Any

import utils


class TensorBoardCallback:
    """Write epoch metrics to TensorBoard when available."""

    def __init__(self, *, log_subdir: str = "tensorboard") -> None:
        self.log_subdir = log_subdir
        self._writer = None
        self._enabled = True

    def _get_writer(self, trainer: Any):
        if not self._enabled:
            return None
        if self._writer is not None:
            return self._writer
        try:
            from torch.utils.tensorboard import SummaryWriter
        except Exception:
            self._enabled = False
            return None
        log_dir = Path(trainer.output_dir) / self.log_subdir
        log_dir.mkdir(parents=True, exist_ok=True)
        self._writer = SummaryWriter(log_dir=str(log_dir))
        return self._writer

    def on_epoch_start(self, *, epoch: int, trainer: Any) -> None:
        del epoch, trainer
        return None

    def on_epoch_end(self, *, epoch: int, metrics: dict, state: dict, trainer: Any) -> None:
        del state
        writer = self._get_writer(trainer)
        if writer is None:
            return
        global_step = getattr(trainer, "global_step", epoch)
        for key, value in metrics.items():
            if isinstance(value, (int, float)):
                writer.add_scalar(f"metrics/{key}", float(value), int(global_step))
        optimizer = getattr(trainer, "optimizer", None)
        if optimizer is not None and getattr(optimizer, "param_groups", None):
            lr = optimizer.param_groups[0].get("lr")
            if lr is not None:
                writer.add_scalar("optimizer/lr", float(lr), int(global_step))
        writer.flush()

    def on_train_end(self, *, trainer: Any) -> None:
        del trainer
        if self._writer is not None:
            self._writer.close()
            self._writer = None


class CheckpointCallback:
    """Save periodic and best checkpoints from trainer state."""

    def __init__(
        self,
        *,
        filename_prefix: str = "model",
        monitor: str = "loss",
        mode: str = "min",
        save_every: int = 0,
    ) -> None:
        self.filename_prefix = filename_prefix
        self.monitor = monitor
        self.mode = mode
        self.save_every = max(0, int(save_every))
        self.best_metric = float("inf") if mode == "min" else float("-inf")

    def on_epoch_start(self, *, epoch: int, trainer: Any) -> None:
        return None

    def on_epoch_end(self, *, epoch: int, metrics: dict, state: dict, trainer: Any) -> None:
        output_dir = Path(trainer.output_dir)
        last_path = output_dir / f"{self.filename_prefix}_last.pt"
        utils.save_checkpoint(state, last_path)

        if self.save_every > 0 and epoch % self.save_every == 0:
            epoch_dir = output_dir / "epochs" / f"epoch{epoch:04d}"
            epoch_dir.mkdir(parents=True, exist_ok=True)
            utils.save_checkpoint(state, epoch_dir / "epoch.pt")

        current = metrics.get(self.monitor)
        if current is None:
            return

        improved = current < self.best_metric if self.mode == "min" else current > self.best_metric
        if improved:
            self.best_metric = current
            state["best_metric"] = self.best_metric
            best_path = output_dir / f"{self.filename_prefix}_best.pt"
            utils.save_checkpoint(state, best_path)

    def on_train_end(self, *, trainer: Any) -> None:
        return None


class VisualizationCallback:
    """Save visualization artifacts generated by trainer-provided callback."""

    def __init__(self, *, every_n_epochs: int = 1, output_subdir: str = "epochs") -> None:
        self.every_n_epochs = max(1, int(every_n_epochs))
        self.output_subdir = output_subdir

    def on_epoch_start(self, *, epoch: int, trainer: Any) -> None:
        return None

    def on_epoch_end(self, *, epoch: int, metrics: dict, state: dict, trainer: Any) -> None:
        if epoch % self.every_n_epochs != 0:
            return
        render_fn = getattr(trainer, "render_visuals", None)
        if not callable(render_fn):
            return

        output_root = Path(trainer.output_dir) / self.output_subdir / f"epoch{epoch:04d}"
        output_root.mkdir(parents=True, exist_ok=True)
        render_fn(output_root=output_root, epoch=epoch, metrics=metrics, state=state)

    def on_train_end(self, *, trainer: Any) -> None:
        return None


class MetricsCSVCallback:
    """Append epoch metrics to a CSV file."""

    def __init__(self, *, filename: str = "metrics.csv", metric_keys: list[str] | None = None) -> None:
        self.filename = filename
        self.metric_keys = metric_keys

    def on_epoch_start(self, *, epoch: int, trainer: Any) -> None:
        return None

    def on_epoch_end(self, *, epoch: int, metrics: dict, state: dict, trainer: Any) -> None:
        output_dir = Path(trainer.output_dir)
        path = output_dir / self.filename
        keys = self.metric_keys or sorted(metrics.keys())

        if not path.exists():
            header = "epoch," + ",".join(keys) + "\n"
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(header, encoding="utf-8")

        row = [str(epoch)]
        for key in keys:
            value = metrics.get(key)
            if value is None:
                row.append("")
            elif isinstance(value, (int, float)):
                row.append(f"{value:.6f}")
            else:
                row.append(str(value))

        with path.open("a", encoding="utf-8") as handle:
            handle.write(",".join(row) + "\n")

    def on_train_end(self, *, trainer: Any) -> None:
        return None


class MultiResolutionCallback:
    """Rebuild dataloaders on multi-resolution stage transitions."""

    def __init__(self) -> None:
        self._last_resolution: int | None = None

    def on_epoch_start(self, *, epoch: int, trainer: Any) -> None:
        schedule = getattr(trainer, "_resolution_schedule", None)
        if schedule is None:
            return
        resolution = int(schedule.current_resolution(epoch))
        if self._last_resolution is None:
            self._last_resolution = resolution
            trainer._rebuild_dataloaders(target_resolution=resolution)
            return
        if resolution != self._last_resolution:
            self._last_resolution = resolution
            trainer._rebuild_dataloaders(target_resolution=resolution)

    def on_epoch_end(self, *, epoch: int, metrics: dict, state: dict, trainer: Any) -> None:
        _ = epoch, metrics, state, trainer
        return None

    def on_train_end(self, *, trainer: Any) -> None:
        _ = trainer
        return None
